package edu.poly.store.domain;
// Generated Nov 19, 2018 3:26:27 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product",
         schema = "dbo",
         catalog = "AssignmentStoreDB"
)
public class Product implements java.io.Serializable {

    private int productId;
    private Category category;
    private Serializable name;
    private int quantity;
    private double price;
    private Date manufacturedDate;

    public Product() {
    }

    public Product(int productId, Category category, Serializable name, int quantity, double price, Date manufacturedDate) {
        this.productId = productId;
        this.category = category;
        this.name = name;
        this.quantity = quantity;
        this.price = price;
        this.manufacturedDate = manufacturedDate;
    }

    @Id
    @Column(name = "ProductID", unique = true, nullable = false)
    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CategoryID", nullable = false)
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @Column(name = "Name", nullable = false)
    public Serializable getName() {
        return this.name;
    }

    public void setName(Serializable name) {
        this.name = name;
    }

    @Column(name = "Quantity", nullable = false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Column(name = "Price", nullable = false, precision = 53, scale = 0)
    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ManufacturedDate", nullable = false, length = 10)
    public Date getManufacturedDate() {
        return this.manufacturedDate;
    }

    public void setManufacturedDate(Date manufacturedDate) {
        this.manufacturedDate = manufacturedDate;
    }

}
